Started work on changing zxfer to work with remote transfers. Added unsupported FreeBSD properties. Alphabetized options in man page.

diff --git a/zxfer b/zxfer
--- a/zxfer
+++ b/zxfer
@@ -1,7 +1,7 @@
 #!/bin/sh
 # BSD HEADER START
 
-# Copyright (c) 2010, Ivan Nash Dreckman
+# Copyright (c) 2010,2011 Ivan Nash Dreckman
 # Copyright (c) 2007, 2008 Constantin Gonzalez
 # All rights reserved.
 
@@ -95,7 +95,7 @@
 #           Where destination is a ZFS filesystem e.g.  poolname/fsname
 
 # zxfer version
-zxfer_version="0.9.0"
+zxfer_version="0.9.2"
 
 # Default values
 option_l=0
@@ -116,6 +116,7 @@ option_k=0
 option_e=0
 option_u=0
 option_b=0
+option_B=0
 exit_status=1 # defaults to failure
 
 services=""
@@ -159,15 +160,15 @@ version,volsize,mountpoint,mlslabel,keysource,keystatus,rekeydate,encryption"
 
 
 # Properties not supported on FreeBSD 8.0
-fbsd_readonly_properties="devices,aclmode,aclinherit,shareiscsi"
+fbsd_readonly_properties="devices,aclmode,aclinherit,shareiscsi,xattr,vscan,nbmand"
 
 
 #
-# Beeps a success or failure sound.
+# Beeps a success sound if -B enabled, and a failure sound if -b or -B enabled.
 # Takes: $exit_status (0 if success, 1 if failure)
 #
 beep() {
-if [ $option_b -eq 1 ]; then
+if [ $option_b -eq 1 -o $option_B -eq 1 ]; then
   # load the speaker kernel module if not loaded already
   speaker_km_loaded=$(kldstat | grep -c speaker.ko)
   if [ $speaker_km_loaded = "0" ]; then
@@ -176,7 +177,9 @@ if [ $option_b -eq 1 ]; then
 
   # play the appropriate beep
   if [ $exit_status -eq 0 ]; then
-    echo "T255CCMLEG~EG..." > /dev/speaker # success sound
+    if [ $option_B -eq 1 ]; then
+      echo "T255CCMLEG~EG..." > /dev/speaker # success sound
+    fi
   else
     echo "T150A<C.." > /dev/speaker # failure sound
   fi
@@ -190,10 +193,10 @@ fi
 usage() {
 cat <<EOT
 usage: 
-     zxfer [-bFdnPsv] [-k | -e] {-N path/to/src | -R path/to/src}
-           [-m [c FMRI|pattern[ FMRI|pattern]...]]] [-r host]
+     zxfer [-FdnPsv] [-k | -e] [-b | -B] {-N path/to/src | -R path/to/src}
+           [-m [c FMRI|pattern[ FMRI|pattern]...]]] [-r user@host]
            [-o option1=value1,option2=value2...] destination
-     zxfer {-S} [-bdvPnl] [-k | -e] [-f /path/to/rsfile]
+     zxfer {-S} [-dvPnl] [-k | -e] [-b | -B] [-f /path/to/rsfile]
            {-R /path/to/src1,path/to/src2... | -N /path/to/src1,path/to/src2...}
            [-o option1=value1,option2=value2...] [-L value] [-u snapshot]
            destination
@@ -250,6 +253,13 @@ consistency_check() {
 # disallow backup and restore of properties at same time
 if [ $option_k -eq 1 -a $option_e -eq 1 ]; then
   echo "Error: You cannot bac(k)up and r(e)store properties at the same time."
+  usage
+  exit 1
+fi
+
+# disallow both beep modes, enforce using one or the other.
+if [ $option_b -eq 1 -a $option_B -eq 1 ]; then
+  echo "Error: You cannot use both beep modes at the same time."
   usage
   exit 1
 fi
@@ -640,7 +650,7 @@ specify is \"2\"."
 
   # for recursive option
   zfs_list_Ho_name=$($LZFS list -H -o name)
-  zfs_list_Ho_mountpoint=$($LZFS list -Ho mountpoint)
+  lzfs_list_Ho_mountpoint=$($LZFS list -Ho mountpoint)
 
   initial_source=$root_fs
   recursive_source_list=$($LZFS list -Hr -o name $root_fs \
@@ -674,7 +684,7 @@ rsync_transfer() {
   # long as we aren't trying to recursively transfer "/", we should be fine.
 
   # is the source (directory) a filesystem?
-  is_fs=$(echo $zfs_list_Ho_mountpoint | tr " " "\n" | grep -c ^$opt_source$)
+  is_fs=$(echo $lzfs_list_Ho_mountpoint | tr " " "\n" | grep -c ^$opt_source$)
 
   if [ $source_type = "r" -a $is_fs -eq "1" ]; then
     # the directory is a filesystem - need to include all fs under source fs
@@ -963,7 +973,6 @@ $source,$actual_dest,$source_pvs"
   fi
 
   valid_option_property=0
-
   #change the field separator to a ","
   OLDIFS=$IFS
   IFS=","
@@ -989,6 +998,7 @@ $source,$actual_dest,$source_pvs"
       fi
     done
   fi
+
 
   # Create the override_pvs list and creation_pvs list.
   # creation_pvs will be used in the instance where we need to create the 
@@ -1066,12 +1076,23 @@ $override_value=$override_source,"
       # we have now transferred all properties
       echov "Creating destination filesystem \"$actual_dest\" \
   with specified properties."
+
+      # revert to old field separator
+      # (This and reversion back is so that $RZFS command works with -r)
+      IFS=$OLDIFS
+
       if [ $option_n -eq 0 ]; then
         eval "$RZFS create $override_option_list $actual_dest" || \
           { echo "Error when creating destination filesystem."; beep; exit 1; }
       else
         echo "$RZFS create $override_option_list $actual_dest"
       fi
+
+      #change the field separator to a ","
+      OLDIFS=$IFS
+      IFS=","
+      
+
     else 
       # for non-initial source, all the overrides will be inherited, hence
       # create with creation_pvs list
@@ -1085,6 +1106,11 @@ $override_value=$override_source,"
         creation_option_list=" -o $creation_option_list"
       fi
 
+
+      # revert to old field separator
+      # (This and reversion back is so that $RZFS command works with -r)
+      IFS=$OLDIFS
+
       echov "Creating destination filesystem \"$actual_dest\" \
 with specified properties."
       if [ $option_n -eq 0 ]; then
@@ -1093,8 +1119,13 @@ with specified properties."
       else
         echo "$RZFS create -p $creation_option_list $actual_dest"
       fi
+
+      #change the field separator to a ","
+      OLDIFS=$IFS
+      IFS=","
     fi
   else # it does exist, need to create.
+    
 
     # For the child, we need to do:
     # If the destination list does exist, we need to do the following:
@@ -1109,7 +1140,18 @@ with specified properties."
     #      is "local". This applies both to -P properties and -o properties
     # 3. If either of those are different, we need to set them.
 
-    dest_pvs=$($RZFS get -Ho property,value,source all "$actual_dest" | tr -s "\t" "=" | tr -s "\n" ",")
+
+    # revert to old field separator
+    # (This and reversion back is so that $RZFS command works with -r)
+    IFS=$OLDIFS
+
+    dest_pvs=$($RZFS get -Ho property,value,source all "$actual_dest")
+
+    #change the field separator to a ","
+    OLDIFS=$IFS
+    IFS=","
+
+    dest_pvs=$(echo "$dest_pvs" | tr -s "\t" "=" | tr -s "\n" ",")
     dest_pvs=$(echo "$dest_pvs" | sed -e 's/,$//g')
 
     # remove the readonly properties and values as we are not comparing to them
@@ -1246,6 +1288,11 @@ with specified properties."
     for ov_line in $ov_set_list; do
       ov_property=$(echo "$ov_line" | cut -f1 -d=)
       ov_value=$(echo "$ov_line" | cut -f2 -d=)
+
+      # revert to old field separator 
+      # (This and reversion back is so that $RZFS command works with -r)
+      IFS=$OLDIFS
+
       if [ $option_n -eq 0 ]; then
         $RZFS set $ov_property=$ov_value $actual_dest || \
         { echo "Error when setting properties on destination filesystem.";\
@@ -1253,6 +1300,11 @@ with specified properties."
       else
         echo "$RZFS set $ov_property=$ov_value $actual_dest"
       fi
+
+      #change the field separator to a ","
+      OLDIFS=$IFS
+      IFS=","
+
     done
 
     if [ "$initial_source" != "$source" ]; then
@@ -1261,6 +1313,11 @@ with specified properties."
       for ov_line in $ov_inherit_list; do
         ov_property=$(echo "$ov_line" | cut -f1 -d=)
         ov_value=$(echo "$ov_line" | cut -f2 -d=)
+
+        # revert to old field separator 
+        # (This and reversion back is so that $RZFS command works with -r)
+        IFS=$OLDIFS
+
         if [ $option_n -eq 0 ]; then
            $RZFS inherit $ov_property $actual_dest || \
             { echo "Error when inheriting properties on destination \
@@ -1268,6 +1325,11 @@ filesystem."; beep; exit 1; }
         else
           echo "$RZFS inherit $ov_property $actual_dest"
         fi
+
+        #change the field separator to a ","
+        OLDIFS=$IFS
+        IFS=","
+
       done
     fi
   fi
@@ -1354,7 +1416,7 @@ $backup_file_extension.$suspect_fs_tail)
 #
 
 # Read command line switches
-while getopts L:SPN:o:R:f:dcFhmnsbu:vekr:l?: i
+while getopts L:SPN:o:R:f:dcFhmnsbBu:vekr:l?: i
 do
   case $i in
     L)
@@ -1429,6 +1491,9 @@ do
       ;;
     b)
       option_b=1
+      ;;
+    B)
+      option_B=1
       ;;
     \?)
       usage
@@ -1722,7 +1787,7 @@ else
     for source in $recursive_source_list; do
       # unmount the source filesystem before doing the last snapshot.
       echov "Unmounting $source."
-      zfs unmount $source || \
+      $LZFS unmount $source || \
         { echo "Couldn't unmount source $source."; relaunch; exit 1; }
     done
   
@@ -1767,13 +1832,13 @@ else
     # If using the -m feature, check if the source is mounted, 
     # otherwise there's no point in us doing the remounting.
     if [ $option_m -eq 1 ]; then
-      source_to_migrate_mounted=$(zfs get -Ho value mounted $source)
+      source_to_migrate_mounted=$($LZFS get -Ho value mounted $source)
       if [ "$source_to_migrate_mounted" = "yes" ]; then
         echo "The source filesystem is not mounted, why use -m?"
 	exit 1
       fi
-      mountpoint=`zfs get -Ho value mountpoint $source`
-      propsource=`zfs get -Ho source mountpoint $source`
+      mountpoint=`$LZFS get -Ho value mountpoint $source`
+      propsource=`$LZFS get -Ho source mountpoint $source`
       echov "Mountpoint is: $mountpoint. Source: $propsource."
     fi
   
