Added the -g option, and other things. Ready for commit as 0.9.7.

diff --git a/zxfer b/zxfer
--- a/zxfer
+++ b/zxfer
@@ -78,10 +78,11 @@
 # or "zfs set" will have the source stay as default while others are 
 # set to local. This does not have any real impacts because these properties
 # are not inheritable. See definition for $fbsd_readonly_properties. 
-
+#
 #     zxfer [-FdnPsv] [-k | -e] [-b | -B] {-N path/to/src | -R path/to/src}
 #           [-m [c FMRI|pattern[ FMRI|pattern]...]]] [-O user@host]
-#           [-T user@host] [-o option1=value1,option2=value2...] destination
+#           [-T user@host] [-o option1=value1,option2=value2...] [-g days]
+#           destination
 #     zxfer {-S} [-dvPnl] [-k | -e] [-b | -B] [-f /path/to/rsfile]
 #           {-R /path/to/src1,path/to/src2... | -N /path/to/src1,path/to/src2...}
 #           [-o option1=value1,option2=value2...] [-L value] [-u snapshot]
@@ -89,6 +90,7 @@
 #     zxfer [-h]
 #
 #           Where destination is a ZFS filesystem e.g.  poolname/fsname
+#
 
 # zxfer version
 zxfer_version="0.9.7"
@@ -99,6 +101,7 @@ option_B=0
 option_d=0
 option_e=0
 option_f=""
+option_g=""
 option_F=""
 option_k=0
 option_l=0
@@ -141,6 +144,8 @@ RZFS=$LZFS
 
 LCAT=""
 AWK=$( ${WHICH} awk )   # location of awk or gawk on home OS
+
+current_date=$(date +%s)  # current date in seconds from 1970
 
 # specific to rsync mode
 snapshot_name="zxfertempsnap"
@@ -472,6 +477,41 @@ newsnap() {
 
 
 #
+# Tests a snapshot to see if it is older than the grandfather option allows for.
+# Takes $ds, (a destination shapshot)
+#
+grandfather_test() {
+  ds=$1
+  snap_date=$($RZFS get -H -o value -p creation $ds)
+  diff_sec=$((current_date-snap_date))
+  diff_day=$((diff_sec/86400))
+  if [ $diff_day -ge $option_g ]; then
+    snap_date_english=$($RZFS get -H -o value creation $ds)
+    current_date_english=$(date)
+    echo "Error: On the destination there is a snapshot marked for destruction"
+    echo "by zxfer that is protected by the use of the \"grandfather"
+    echo "protection\" option, -g."
+    echo
+    echo "You have set grandfather protection at $option_g days."
+    echo "Snapshot name: $ds"
+    echo "Snapshot age : $diff_day days old"
+    echo "Snapshot date: $snap_date_english." 
+    echo "Your current system date: $current_date_english."  
+    echo
+    echo "Either amend/remove option g, fix your system date, or manually"
+    echo "destroy the offending snapshot. Also double check that your"
+    echo "snapshot management tool isn't erroneously deleting source snapshots."
+    echo "Note that for option g to work correctly, you should set it just"
+    echo "above a number of days that will preclude \"son\" snapshots from"
+    echo "being encountered."
+    echo
+    usage; beep
+    exit 1
+  fi
+}
+
+
+#
 # Find the most recent common snapshot on source and destination.
 # Then, create a list of snapshots on source, starting from the
 # one after the most recent common snapshot.
@@ -481,7 +521,8 @@ newsnap() {
 inspect_delete_snap() {
 
   # Get the list of source snapshots 
-  zfs_source_snaps=$(echo "$lzfs_list_hr_S_snap" | grep ^$source@) > /dev/null 2>&1
+  zfs_source_snaps=$(echo "$lzfs_list_hr_S_snap" | \
+grep ^$source@) > /dev/null 2>&1
 
   # save a copy for when we need to make a new list
   zfs_source_snaps_orig=$zfs_source_snaps
@@ -510,14 +551,19 @@ inspect_delete_snap() {
           last_common_snap=`echo $dest_snap | grep @ | cut -d@ -f2`
         fi
 
-        # since the snap was matched, let's not waste our time searching for it again
+        # since the snap was matched, let's not waste our time searching for 
+	# it again
         zfs_source_snaps=$(echo "$zfs_source_snaps" | grep -v "$src_snap")
 
-        # let's also break out of the loop, since we've already found what we are looking for
+        # let's also break out of the loop, since we've already found what we 
+	# are looking for
         break
       fi
     done
     if [ $mark_snap_for_deletion = 1 -a $option_d -eq 1 ]; then
+      if [ "$option_g" != "" ]; then
+        grandfather_test $dest_snap
+      fi
       echov "Destroying destination snapshot $dest_snap."
       if [ $option_n -eq 0 ]; then
         $RZFS destroy $dest_snap || \
@@ -1507,8 +1553,7 @@ $backup_file_dir/$backup_file_extension.$is_tail\" | $option_T sh"
 #
 
 # Read command line switches
-#while getopts L:SPN:o:R:f:dcFhmnsbBu:vekT:O:l?: i
-while getopts bBc:def:FhklL:lmnN:o:O:PPR:sST:u:v?: i
+while getopts bBc:def:g:FhklL:lmnN:o:O:PPR:sST:u:v?: i
 do
   case $i in
     b)
@@ -1534,6 +1579,9 @@ do
       ;;
     F)
       option_F="-F"
+      ;;
+    g)
+      option_g="$OPTARG"
       ;;
     h)
       usage
